package site.silverbot.api.dashboard.controller;

import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.document;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.restdocs.mockmvc.RestDocumentationRequestBuilders;
import org.springframework.security.test.context.support.WithMockUser;

import site.silverbot.domain.elder.Elder;
import site.silverbot.domain.elder.ElderRepository;
import site.silverbot.domain.elder.Gender;
import site.silverbot.domain.emergency.EmergencyRepository;
import site.silverbot.domain.robot.NetworkStatus;
import site.silverbot.domain.robot.Robot;
import site.silverbot.domain.robot.RobotRepository;
import site.silverbot.domain.user.User;
import site.silverbot.domain.user.UserRepository;
import site.silverbot.domain.user.UserRole;
import site.silverbot.support.RestDocsSupport;

class DashboardControllerTest extends RestDocsSupport {

    @Autowired
    private ElderRepository elderRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private EmergencyRepository emergencyRepository;

    @Autowired
    private RobotRepository robotRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private Elder elder;

    @BeforeEach
    void setUp() {
        ensurePhase2Tables();
        clearPhase2Tables();

        emergencyRepository.deleteAllInBatch();
        robotRepository.deleteAllInBatch();
        elderRepository.deleteAllInBatch();
        userRepository.deleteAllInBatch();

        User user = userRepository.save(User.builder()
                .name("김복지")
                .email("worker@test.com")
                .password("password")
                .role(UserRole.WORKER)
                .build());

        elder = elderRepository.save(Elder.builder()
                .user(user)
                .name("김옥분")
                .birthDate(LocalDate.of(1946, 5, 15))
                .gender(Gender.FEMALE)
                .build());

        robotRepository.save(Robot.builder()
                .elder(elder)
                .serialNumber("RB-0001")
                .networkStatus(NetworkStatus.CONNECTED)
                .batteryLevel(78)
                .currentLocation("거실")
                .lastSyncAt(LocalDateTime.now())
                .build());

        insertMedication(elder.getId(), "혈압약", "1정", "MORNING", LocalDate.now(), null);
        insertNotification(user.getId(), elder.getId(), "MEDICATION", "복약 알림", "아침 복약 시간이 되었습니다.");
        insertSchedule(elder.getId(), "병원 예약", LocalDateTime.now().plusDays(1), "서울대병원", "HOSPITAL", "UPCOMING");
        insertWakeUpActivity(elder.getId(), LocalDateTime.now().withHour(7).withMinute(20).withSecond(0).withNano(0));
    }

    @Test
    @WithMockUser(username = "worker@test.com", roles = {"WORKER"})
    void getDashboard_returnsIntegratedData() throws Exception {
        mockMvc.perform(RestDocumentationRequestBuilders.get("/api/elders/{elderId}/dashboard", elder.getId()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.data.todaySummary").exists())
                .andExpect(jsonPath("$.data.recentNotifications.length()").value(1))
                .andExpect(jsonPath("$.data.weeklySchedules.length()").value(1))
                .andExpect(jsonPath("$.data.robotStatus.batteryLevel").value(78))
                .andDo(document("dashboard-get"));
    }

    private void ensurePhase2Tables() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS medication (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    elder_id BIGINT NOT NULL,
                    name VARCHAR(100) NOT NULL,
                    dosage VARCHAR(100) NOT NULL,
                    frequency VARCHAR(20) NOT NULL,
                    timing VARCHAR(100),
                    color VARCHAR(30),
                    start_date DATE,
                    end_date DATE,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS medication_record (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    elder_id BIGINT NOT NULL,
                    medication_id BIGINT NOT NULL,
                    record_date DATE NOT NULL,
                    time_of_day VARCHAR(20) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    taken_at TIMESTAMP,
                    method VARCHAR(20),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uk_medication_record UNIQUE (medication_id, record_date, time_of_day)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS schedule (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    elder_id BIGINT NOT NULL,
                    title VARCHAR(120) NOT NULL,
                    description CLOB,
                    scheduled_at TIMESTAMP NOT NULL,
                    location VARCHAR(120),
                    type VARCHAR(30) NOT NULL,
                    source VARCHAR(30),
                    status VARCHAR(30) NOT NULL,
                    remind_before_minutes INT NOT NULL DEFAULT 60,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS notification (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT,
                    elder_id BIGINT,
                    type VARCHAR(30) NOT NULL,
                    title VARCHAR(150) NOT NULL,
                    message CLOB,
                    action_url VARCHAR(255),
                    is_read BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS activity (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    elder_id BIGINT NOT NULL,
                    robot_id BIGINT,
                    type VARCHAR(40) NOT NULL,
                    title VARCHAR(120),
                    description CLOB,
                    location VARCHAR(120),
                    detected_at TIMESTAMP NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    private void clearPhase2Tables() {
        jdbcTemplate.update("DELETE FROM medication_record");
        jdbcTemplate.update("DELETE FROM medication");
        jdbcTemplate.update("DELETE FROM schedule");
        jdbcTemplate.update("DELETE FROM notification");
        jdbcTemplate.update("DELETE FROM activity");
    }

    private void insertMedication(
            Long elderId,
            String name,
            String dosage,
            String frequency,
            LocalDate startDate,
            LocalDate endDate
    ) {
        jdbcTemplate.update(
                """
                INSERT INTO medication (elder_id, name, dosage, frequency, timing, color, start_date, end_date, is_active, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
                elderId,
                name,
                dosage,
                frequency,
                "식후",
                "white",
                startDate,
                endDate,
                true
        );
    }

    private void insertNotification(Long userId, Long elderId, String type, String title, String message) {
        jdbcTemplate.update(
                """
                INSERT INTO notification (user_id, elder_id, type, title, message, is_read, created_at)
                VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
                """,
                userId,
                elderId,
                type,
                title,
                message,
                false
        );
    }

    private void insertSchedule(
            Long elderId,
            String title,
            LocalDateTime scheduledAt,
            String location,
            String type,
            String status
    ) {
        jdbcTemplate.update(
                """
                INSERT INTO schedule (
                    elder_id, title, scheduled_at, location, type, source, status,
                    remind_before_minutes, created_at, updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
                elderId,
                title,
                scheduledAt,
                location,
                type,
                "MANUAL",
                status,
                60
        );
    }

    private void insertWakeUpActivity(Long elderId, LocalDateTime detectedAt) {
        jdbcTemplate.update(
                """
                INSERT INTO activity (elder_id, type, title, detected_at, created_at)
                VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
                """,
                elderId,
                "WAKE_UP",
                "기상",
                detectedAt
        );
    }
}
