CREATE TYPE user_role AS ENUM ('WORKER', 'FAMILY');
CREATE TYPE theme_mode AS ENUM ('SYSTEM', 'LIGHT', 'DARK');

CREATE TYPE elder_status AS ENUM ('SAFE', 'WARNING', 'DANGER');
CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');

CREATE TYPE network_status AS ENUM ('CONNECTED', 'DISCONNECTED');
CREATE TYPE lcd_mode AS ENUM ('IDLE', 'GREETING', 'MEDICATION', 'SCHEDULE', 'LISTENING', 'EMERGENCY', 'SLEEP');
CREATE TYPE lcd_emotion AS ENUM ('NEUTRAL', 'HAPPY', 'SLEEP');

CREATE TYPE room_type AS ENUM ('LIVING_ROOM', 'KITCHEN', 'BEDROOM', 'BATHROOM', 'ENTRANCE', 'DOCK');

CREATE TYPE command_type AS ENUM ('MOVE_TO', 'START_PATROL', 'RETURN_TO_DOCK', 'SPEAK', 'CHANGE_LCD_MODE');
CREATE TYPE command_status AS ENUM ('PENDING', 'RECEIVED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED');

CREATE TYPE emergency_type AS ENUM ('FALL_DETECTED', 'NO_RESPONSE', 'SOS_BUTTON', 'UNUSUAL_PATTERN');
CREATE TYPE emergency_resolution AS ENUM ('PENDING', 'FALSE_ALARM', 'RESOLVED', 'EMERGENCY_CALLED', 'FAMILY_CONTACTED');
